services:
  - type: web
    name: whatsbixby
    env: node
    branch: master
    repo: https://github.com/DX-MODS/WhatsBixby.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: WORK_TYPE
        sync: false
      - key: SUDO
        sync: false
      - key: LANGUAGE
        sync: false
      - key: HANDLERS
        sync: false
      - key: API_KEY
        sync: false
      - key: PACKNAME
        sync: false
      - key: AUTHOR
        sync: false
